---
# Level 1 Diagnosis for Windows and Linux
- hosts: all
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
  tasks:
    - name: "win_level1diagnosis Level 1 Diagnosis"
      win_level1diagnosis: 
      register: win_l1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "win_level1diagnosis with top Level 1 Diagnosis"
      win_level1diagnosis: 
        topprocessesbycpu: 3
        topprocessesbymem: 3
        checklogicaldisk: e
      register: top_l1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Python Level 1 Diagnosis"
      l1diagnosis:
      register: l1_info
      when: os_type != "Windows"
      ignore_errors: true

    - name: "level1diagnosis Level 1 Diagnosis"
      level1diagnosis:
      register: linux_l1_info
      when: 
        - l1_info is defined
        - not l1_info.success
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: >-
          "{{ inventory_hostname }}": {{ win_l1_info.stdout | to_json }}
      when: win_l1_info is defined
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: >-
          "{{ inventory_hostname }}": {{ l1_info.stdout | to_json }}
      when: l1_info.success
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: >-
          "{{ inventory_hostname }}": {{ linux_l1_info.stdout | to_json }}
      when:
        - l1_info is defined
        - not l1_info.success
      ignore_errors: true

    - name: Set facts for event acknowledgement
      set_fact:
        slack_token: "{{ lookup('env','s_token') }}"
      run_once: true
      delegate_to: localhost
      ignore_errors: true
      no_log: true

    - name: Send message to slack
      slack:
        token: "{{ slack_token }}"
        attachments:
          - text: "{{ hostvars[inventory_hostname]['job_msg'] }}" 
            title: Launched {{ tower_job_id }}
        channel: "automation"
        domain: "app.slack.com"
      delegate_to: localhost
      ignore_errors: true

    - name: stats
      set_stats: 
        data:
          stats: "{{ job_msg }}"
      ignore_errors: true